version: "3.9"

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: fastapi_local
    command: /bin/sh -c "tail -f /dev/null"
    volumes:
      - .:/app   # mount code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.local

  db:
    image: mysql:8.0.44-debian
    container_name: fastapi_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: file_compare_db
    ports:
      - "3336:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./data/backup:/backup

volumes:
  db_data:
